version: '3.8'
services:
  php:
    image: johnoliveira/appphp:1.0.0
    container_name: app-php
    networks:
      - php_net
  nginx:
    image: nginx:1.21.6-alpine
    container_name: app-nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/assets:/var/www/html/assets
    networks:
      - php_net

networks:
  php_net:
    driver: bridge