version: '3.8'
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: app-php
    volumes:
      - ./src:/var/www/html/src
  nginx:
    image: nginx:1.21.6-alpine
    container_name: app-nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/assets:/var/www/html/assets