version: '3.8'
services:
  php:
    image: php:8.1.3-fpm-alpine
    container_name: app-php
    volumes:
      - ./src:/usr/share/nginx/html
  nginx:
    image: nginx:1.21.6-alpine
    container_name: app-nginx
    ports:
      - 80:80
    volumes:
      - ./nginx:/etc/nginx/conf.d